import os
import sys
import json
import sqlite3
import datetime
import logging
from typing import Optional, List, Dict, Any

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv

# Charge les variables d'environnement (.env)
load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
OWNER_IDS = [int(x.strip()) for x in os.getenv("OWNER_IDS", "").split(",") if x.strip() and x.strip().isdigit()]

# Code secret pour débloquer le pack complet
ACTIVATION_CODE = "0001"

# Configuration du Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("Zyren")

# Support de l'IA Gemini (google-genai)
try:
    from google import genai
    from google.genai import types
    if GEMINI_API_KEY:
        ai_client = genai.Client(api_key=GEMINI_API_KEY)
    else:
        ai_client = None
except ImportError:
    ai_client = None
    logger.warning("Bibliothèque google-genai non disponible. Mode IA local activé.")

# ------------------------------------------------------------------------------
# TRADUCTIONS & MULTILINGUE
# ------------------------------------------------------------------------------

LANGUAGES = {
    "fr": "Français 🇫🇷",
    "en": "English 🇬🇧",
    "ar": "العربية 🇸🇦"
}

TRANSLATIONS = {
    "fr": {
        "welcome_select_lang": "Veuillez sélectionner la langue principale du serveur :",
        "lang_set": "La langue du serveur a été configurée sur : **Français 🇫🇷**",
        "no_permission": "❌ Vous n'avez pas la permission requise (`{perm}`) pour exécuter cette action.",
        "unlock_required": "🔒 **Pack Vérouillé**\nCette option nécessite d'activer le pack complet.\nUtilisez la commande `/redeem 0001` pour tout débloquer !",
        "dash_title": "🤖 ZYREN DASHBOARD",
        "dash_desc": "Bienvenue sur le panneau de contrôle interactif de **Zyren**.\nGérez l'ensemble des fonctionnalités du serveur ci-dessous.",
        "stats_title": "📊 Statistiques du Serveur",
        "ticket_created": "🎫 Votre ticket a été créé : {channel}",
        "ticket_closed": "🔒 Le ticket a été fermé par {user}.",
        "mod_action_success": "✅ L'action `{action}` a été appliquée sur {target}. Raison : {reason}",
        "welcome_msg_default": "Bienvenue {member} sur le serveur **{guild}** !",
        "server_builder_start": "🏗️ **Lia Server Builder** commence l'analyse et la création du serveur...",
        "server_builder_success": "✅ La structure du serveur a été générée avec succès par Lia !"
    },
    "en": {
        "welcome_select_lang": "Please select the primary language for this server:",
        "lang_set": "Server language has been set to: **English 🇬🇧**",
        "no_permission": "❌ You do not have the required permission (`{perm}`).",
        "unlock_required": "🔒 **Locked Pack**\nThis feature requires unlocking the full pack.\nUse `/redeem 0001` to unlock everything!",
        "dash_title": "🤖 ZYREN DASHBOARD",
        "dash_desc": "Welcome to the interactive control panel of **Zyren**.",
        "stats_title": "📊 Server Statistics",
        "ticket_created": "🎫 Your ticket has been created: {channel}",
        "ticket_closed": "🔒 Ticket closed by {user}.",
        "mod_action_success": "✅ Action `{action}` applied to {target}.",
        "welcome_msg_default": "Welcome {member} to **{guild}**!",
        "server_builder_start": "🏗️ **Lia Server Builder** is building structure...",
        "server_builder_success": "✅ Server structure successfully generated by Lia!"
    },
    "ar": {
        "welcome_select_lang": "يرجى اختيار اللغة الرئيسية للسيرفر:",
        "lang_set": "تم ضبط لغة السيرفر إلى: **العربية 🇸🇦**",
        "no_permission": "❌ لا تملك الصلاحيات المطلوبة (`{perm}`).",
        "unlock_required": "🔒 **الحزمة مغلقة**\nتتطلب هذه الميزة تفعيل الحزمة الكاملة.\nاستخدم `/redeem 0001` لفتح كل شيء!",
        "dash_title": "🤖 لوحة تحكم ZYREN",
        "dash_desc": "مرحبًا بك في لوحة التحكم التفاعلية لـ **Zyren**.",
        "stats_title": "📊 إحصائيات السيرفر",
        "ticket_created": "🎫 تم إنشاء تذكرتك: {channel}",
        "ticket_closed": "🔒 تم إغلاق التذكرة بواسطة {user}.",
        "mod_action_success": "✅ تم تطبيق الإجراء `{action}` على {target}.",
        "welcome_msg_default": "أهلاً بك {member} في **{guild}**!",
        "server_builder_start": "🏗️ **Lia Server Builder** يبدأ إنشاء هيكلة السيرفر...",
        "server_builder_success": "✅ تم إنشاء هيكل السيرفر بنجاح بواسطة Lia!"
    }
}

def get_text(lang: str, key: str, **kwargs) -> str:
    l = lang if lang in TRANSLATIONS else "fr"
    text = TRANSLATIONS[l].get(key, TRANSLATIONS["fr"].get(key, key))
    return text.format(**kwargs)

# ------------------------------------------------------------------------------
# BASE DE DONNÉES (SQLite3)
# ------------------------------------------------------------------------------

class Database:
    def __init__(self, db_path: str = "zyren.db"):
        self.db_path = db_path
        self.init_db()

    def get_connection(self):
        return sqlite3.connect(self.db_path)

    def init_db(self):
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS guild_config (
                guild_id INTEGER PRIMARY KEY,
                language TEXT DEFAULT 'fr',
                ia_enabled INTEGER DEFAULT 1,
                unlocked INTEGER DEFAULT 0,
                welcome_channel_id INTEGER DEFAULT 0,
                welcome_message TEXT DEFAULT '',
                auto_role_id INTEGER DEFAULT 0,
                ticket_category_id INTEGER DEFAULT 0,
                ticket_support_role_id INTEGER DEFAULT 0,
                announce_channel_id INTEGER DEFAULT 0,
                mod_logs_channel_id INTEGER DEFAULT 0
            )
            """)
            conn.commit()

    def get_guild_config(self, guild_id: int) -> Dict[str, Any]:
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM guild_config WHERE guild_id = ?", (guild_id,))
            row = cursor.fetchone()
            if not row:
                cursor.execute("INSERT INTO guild_config (guild_id) VALUES (?)", (guild_id,))
                conn.commit()
                return self.get_guild_config(guild_id)
            
            return {
                "guild_id": row[0],
                "language": row[1],
                "ia_enabled": bool(row[2]),
                "unlocked": bool(row[3]),
                "welcome_channel_id": row[4],
                "welcome_message": row[5],
                "auto_role_id": row[6],
                "ticket_category_id": row[7],
                "ticket_support_role_id": row[8],
                "announce_channel_id": row[9],
                "mod_logs_channel_id": row[10]
            }

    def update_guild_config(self, guild_id: int, key: str, value: Any):
        with self.get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(f"UPDATE guild_config SET {key} = ? WHERE guild_id = ?", (value, guild_id))
            conn.commit()

    def is_unlocked(self, guild_id: int, user_id: Optional[int] = None) -> bool:
        # Le Créateur a toujours accès à tout gratuitement
        if user_id and user_id in OWNER_IDS:
            return True
        config = self.get_guild_config(guild_id)
        return config["unlocked"]

db = Database()

# ------------------------------------------------------------------------------
# CORE IA: LIA ENGINE
# ------------------------------------------------------------------------------

class LiaEngine:
    @staticmethod
    async def generate_response(prompt: str, system_instruction: str = "") -> str:
        if not ai_client:
            return "[Lia Engine]: API Gemini non disponible."
        try:
            config = types.GenerateContentConfig(
                system_instruction=system_instruction or "Tu es Lia, l'intelligence artificielle intégrée au bot Discord Zyren."
            )
            response = ai_client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
                config=config
            )
            return response.text
        except Exception as e:
            logger.error(f"Erreur Lia Engine : {e}")
            return "Une erreur est survenue lors de la génération avec Lia."

    @staticmethod
    async def parse_server_structure(description: str) -> Dict[str, Any]:
        system_prompt = (
            "Tu es Lia, l'expert en architecture Discord de Zyren. "
            "Analyse le texte et génère STRICTEMENT un objet JSON valide :\n"
            '{"roles": ["Role1", "Role2"], "categories": [{"name": "Cat1", "channels": [{"name": "ch-1", "type": "text"}]}]}'
        )
        if not ai_client:
            return {
                "roles": ["Membre", "Staff"],
                "categories": [{"name": "📌 ACCUEIL", "channels": [{"name": "bienvenue", "type": "text"}]}]
            }

        res = await LiaEngine.generate_response(description, system_instruction=system_prompt)
        try:
            start = res.find("{")
            end = res.rfind("}") + 1
            return json.loads(res[start:end])
        except Exception:
            return {"roles": ["Membre"], "categories": [{"name": "GÉNÉRAL", "channels": [{"name": "discussion", "type": "text"}]}]}

# ------------------------------------------------------------------------------
# INTERFACES UTILISATEUR DISCORD (UI)
# ------------------------------------------------------------------------------

class LanguageSelectView(discord.ui.View):
    def __init__(self, guild_id: int):
        super().__init__(timeout=180)
        self.guild_id = guild_id

    @discord.ui.select(
        placeholder="Choisissez la langue...",
        options=[
            discord.SelectOption(label="Français", value="fr", emoji="🇫🇷"),
            discord.SelectOption(label="English", value="en", emoji="🇬🇧"),
            discord.SelectOption(label="العربية", value="ar", emoji="🇸🇦"),
        ]
    )
    async def select_callback(self, interaction: discord.Interaction, select: discord.ui.Select):
        db.update_guild_config(self.guild_id, "language", select.values[0])
        await interaction.response.send_message(get_text(select.values[0], "lang_set"), ephemeral=True)

class ServerBuilderModal(discord.ui.Modal, title="🏗️ Lia Server Builder"):
    prompt_input = discord.ui.TextInput(
        label="Description de votre serveur",
        style=discord.TextStyle.paragraph,
        placeholder="Ex: Serveur Gaming avec zone Staff et salons vocaux...",
        required=True,
        max_length=1000
    )

    async def on_submit(self, interaction: discord.Interaction):
        unlocked = db.is_unlocked(interaction.guild_id, interaction.user.id)
        config = db.get_guild_config(interaction.guild_id)
        lang = config["language"]

        if not unlocked:
            await interaction.response.send_message(get_text(lang, "unlock_required"), ephemeral=True)
            return

        await interaction.response.send_message(get_text(lang, "server_builder_start"), ephemeral=True)
        structure = await LiaEngine.parse_server_structure(self.prompt_input.value)

        try:
            for r_name in structure.get("roles", []):
                await interaction.guild.create_role(name=r_name, reason="Lia Builder")
            for cat in structure.get("categories", []):
                category = await interaction.guild.create_category(cat["name"])
                for ch in cat.get("channels", []):
                    if ch.get("type") == "voice":
                        await category.create_voice_channel(ch["name"])
                    else:
                        await category.create_text_channel(ch["name"])
            await interaction.followup.send(get_text(lang, "server_builder_success"), ephemeral=True)
        except Exception as e:
            logger.error(f"Erreur création : {e}")
            await interaction.followup.send("❌ Permissions insuffisantes pour créer les rôles/salons.", ephemeral=True)

class DashboardView(discord.ui.View):
    def __init__(self, user: discord.User, guild: discord.Guild):
        super().__init__(timeout=300)
        self.user = user
        self.guild = guild
        self.config = db.get_guild_config(guild.id)
        self.lang = self.config["language"]
        self.unlocked = db.is_unlocked(guild.id, user.id)

    @discord.ui.button(label="Statistiques", style=discord.ButtonStyle.secondary, emoji="📊", row=0)
    async def stats_btn(self, interaction: discord.Interaction, button: discord.ui.Button):
        embed = discord.Embed(title=get_text(self.lang, "stats_title"), color=discord.Color.blue())
        embed.add_field(name="Membres", value=str(self.guild.member_count), inline=True)
        embed.add_field(name="Statut Pack", value="🔓 **DÉBLOQUÉ**" if self.unlocked else "🔒 **VERROUILLÉ**", inline=True)
        await interaction.response.send_message(embed=embed, ephemeral=True)

    @discord.ui.button(label="Lia IA", style=discord.ButtonStyle.primary, emoji="🧠", row=0)
    async def lia_btn(self, interaction: discord.Interaction, button: discord.ui.Button):
        if not self.unlocked:
            await interaction.response.send_message(get_text(self.lang, "unlock_required"), ephemeral=True)
            return
        await interaction.response.send_message("🧠 **Lia IA** est débloquée et prête à être utilisée !", ephemeral=True)

    @discord.ui.button(label="Créer Serveur", style=discord.ButtonStyle.success, emoji="🏗️", row=1)
    async def build_btn(self, interaction: discord.Interaction, button: discord.ui.Button):
        if not self.unlocked:
            await interaction.response.send_message(get_text(self.lang, "unlock_required"), ephemeral=True)
            return
        await interaction.response.send_modal(ServerBuilderModal())

    @discord.ui.button(label="Langue", style=discord.ButtonStyle.secondary, emoji="🌍", row=1)
    async def lang_btn(self, interaction: discord.Interaction, button: discord.ui.Button):
        view = LanguageSelectView(self.guild.id)
        await interaction.response.send_message(get_text(self.lang, "welcome_select_lang"), view=view, ephemeral=True)

# ------------------------------------------------------------------------------
# BOT MAIN CLASS
# ------------------------------------------------------------------------------

class ZyrenBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.message_content = True
        intents.guilds = True
        intents.members = True
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self):
        await self.tree.sync()

    async def on_ready(self):
        logger.info(f"⚡ Zyren connecté sous {self.user} (ID: {self.user.id})")
        logger.info(f"👑 Créateur(s) reconnu(s) : {OWNER_IDS}")
        await self.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="/dashboard | Zyren & Lia"))

bot = ZyrenBot()

# ------------------------------------------------------------------------------
# COMMANDES SLASH
# ------------------------------------------------------------------------------

@bot.tree.command(name="dashboard", description="Panneau de configuration interactif Zyren.")
async def dashboard_cmd(interaction: discord.Interaction):
    config = db.get_guild_config(interaction.guild_id)
    unlocked = db.is_unlocked(interaction.guild_id, interaction.user.id)
    
    is_owner = interaction.user.id in OWNER_IDS
    title = get_text(config["language"], "dash_title")
    if is_owner:
        title += " 👑 [MODE CRÉATEUR - ACCÈS TOTAL]"

    embed = discord.Embed(
        title=title,
        description=get_text(config["language"], "dash_desc"),
        color=discord.Color.green() if unlocked else discord.Color.dark_gray()
    )
    embed.add_field(name="Statut Pack", value="🟢 **DÉBLOQUÉ (Créateur)**" if is_owner else ("🟢 **DÉBLOQUÉ**" if unlocked else "🔴 **VERROUILLÉ**"), inline=True)
    embed.add_field(name="Langue", value=LANGUAGES.get(config["language"], "Français 🇫🇷"), inline=True)

    view = DashboardView(interaction.user, interaction.guild)
    await interaction.response.send_message(embed=embed, view=view, ephemeral=True)

@bot.tree.command(name="redeem", description="Entrer le code de déverrouillage pour débloquer Lia et toutes les fonctionnalités.")
@app_commands.describe(code="Entrez le code à chiffres (Ex: 0001)")
async def redeem_cmd(interaction: discord.Interaction, code: str):
    if code.strip() == ACTIVATION_CODE:
        db.update_guild_config(interaction.guild_id, "unlocked", 1)
        embed = discord.Embed(
            title="🎉 Code Correct !",
            description="Le code **0001** a été validé avec succès !\n\nToutes les fonctionnalités du bot (**Lia IA**, **Création de Serveur**, etc.) sont désormais **débloquées sur ce serveur** !",
            color=discord.Color.green()
        )
        await interaction.response.send_message(embed=embed, ephemeral=True)
    else:
        await interaction.response.send_message("❌ Code incorrect ! Veuillez entrer le bon code pour débloquer le pack.", ephemeral=True)

# ---------------- COMMANDES PROPRIÉTAIRE (OWNER ONLY) ----------------

@bot.tree.command(name="owner-dashboard", description="[OWNER ONLY] Panneau d'administration global.")
async def owner_dashboard_cmd(interaction: discord.Interaction):
    if interaction.user.id not in OWNER_IDS:
        await interaction.response.send_message("⛔ Accès refusé. Réservé au Créateur du bot.", ephemeral=True)
        return

    embed = discord.Embed(
        title="👑 ZYREN OWNER DASHBOARD",
        description=f"**Serveurs connectés :** `{len(bot.guilds)}`",
        color=discord.Color.red()
    )
    for g in bot.guilds[:10]:
        embed.add_field(name=g.name, value=f"ID: `{g.id}` | Membres: {g.member_count}", inline=False)

    await interaction.response.send_message(embed=embed, ephemeral=True)

# ---------------- EXECUTION ----------------

if __name__ == "__main__":
    if not DISCORD_TOKEN:
        logger.critical("❌ Aucun DISCORD_TOKEN trouvé dans le fichier .env !")
        sys.exit(1)
        
    bot.run(DISCORD_TOKEN)
